### ISSUE TITLE
Just had a Grott HA update, now not working

### ISSUE THREAD

**Issue by chesterflaps** [egguy/grott-home-assistant-add-on#41]
I have just updated Grott in HA and now when I start the Grott add on, it stops after a few minutes and I get no solar information.

Tried a reboot.

**Comment by chesterflaps** [comment]
this is the Grott log

Grott Growatt logging monitor : 2.7.8
Grott process configuration file
Traceback (most recent call last):
  File "/app/grott.py", line 24, in <module>
    conf = Conf(verrel)
           ^^^^^^^^^^^^
  File "/app/grottconf.py", line 94, in __init__
    self.procconf()
  File "/app/grottconf.py", line 359, in procconf
    config.read(self.cfgfile)
  File "/usr/lib/python3.11/configparser.py", line 713, in read
    self._read(fp, filename)
  File "/usr/lib/python3.11/configparser.py", line 1101, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/config/grott/grott.ini', line: 1
'mqttinverterintopic="True"'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
